/*
AWS::WAFRegional::ByteMatchSet
AWS::WAFRegional::IPSet
AWS::WAFRegional::Rule
AWS::WAFRegional::SizeConstraintSet
AWS::WAFRegional::SqlInjectionMatchSet
AWS::WAFRegional::WebACL
AWS::WAFRegional::WebACLAssociation
AWS::WAFRegional::XssMatchSet
*/
